AWSTemplateFormatVersion: '2010-09-09'
Description: Go Lambda behind API Gateway

Parameters:
  LambdaS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda zip
  LambdaS3Key:
    Type: String
    Description: S3 key (path) for the Lambda zip
  TempDocS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda Docker image (ECR compatible)
  FinalDocS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda Docker image (ECR compatible)     
  EventSourceS3Key:
    Type: String
    Description: S3 key (path) for the Lambda Docker image (ECR compatible)  

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub 'lambda-s3-access-inline-policy-${AWS::StackName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:ListObjects
                  - s3:ListObjectsV2
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:HeadObject
                  - s3:Describe*
                Resource: !Sub "arn:aws:s3:::${LambdaS3Bucket}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket         
                  - s3:ListBucketVersions
                  - s3:GetBucketLocation
                Resource: !Sub "arn:aws:s3:::${LambdaS3Bucket}"

        - PolicyName: !Sub 'lambda-temp-doc-s3-access-inline-policy-${AWS::StackName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:ListObjects
                  - s3:ListObjectsV2
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:HeadObject
                  - s3:Describe*
                Resource: !Sub "arn:aws:s3:::${TempDocS3Bucket}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket         
                  - s3:ListBucketVersions
                  - s3:GetBucketLocation
                Resource: !Sub "arn:aws:s3:::${TempDocS3Bucket}"      

        - PolicyName: !Sub 'lambda-final-doc-s3-access-inline-policy-${AWS::StackName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:ListObjects
                  - s3:ListObjectsV2
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:HeadObject
                  - s3:Describe*
                Resource: !Sub "arn:aws:s3:::${FinalDocS3Bucket}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket         
                  - s3:ListBucketVersions
                  - s3:GetBucketLocation
                Resource: !Sub "arn:aws:s3:::${FinalDocS3Bucket}"                                           

        - PolicyName: deny-log-group-creation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: logs:CreateLogGroup
                Resource: "*"

        - PolicyName: lambda-dynamodb-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt DummyTable.Arn
  StreamLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole   
      Path: "/"         
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole      
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt DummyTable.StreamArn
        - PolicyName: deny-log-group-creation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: logs:CreateLogGroup
                Resource: "*"


  EventSourceDummyTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn: !GetAtt DummyTable.StreamArn
      FunctionName: !GetAtt ProcessEventLambda.Arn
      StartingPosition: LATEST

  ProcessEventLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub '/aws/lambda/process-event-lambda-${AWS::StackName}'
      RetentionInDays: 14

  ProcessEventLambda:
    Type: AWS::Lambda::Function
    DependsOn: ProcessEventLambdaLogGroup
    Properties:
      FunctionName: !Sub 'process-event-lambda-${AWS::StackName}'
      Runtime: python3.12
      Timeout: 300
      Handler: eventSource.handler
      Role: !GetAtt StreamLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref EventSourceS3Key



  DummyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dummy-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES    

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub '/aws/lambda/hello-lambda-${AWS::StackName}'
      RetentionInDays: 14

  GoLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub 'hello-lambda-${AWS::StackName}'
      Runtime: provided.al2023
      Handler: bootstrap
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          LOG_LEVEL: INFO
          SOURCE_BUCKET_NAME: !Ref TempDocS3Bucket
          DESTINATION_BUCKET_NAME: !Ref FinalDocS3Bucket
          DYNAMODB_TABLE_NAME: !Ref DummyTable

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn
    

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'hello-api-${AWS::StackName}'
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: "dummy"

  ApiGatewayMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayRootResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations"
          - LambdaArn: !GetAtt GoLambdaFunction.Arn

  ApiGatewayMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayRootResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations"
          - LambdaArn: !GetAtt GoLambdaFunction.Arn    

  MyLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub '${ApiGatewayRestApi}-access-logs'
      RetentionInDays: 14

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethodGet
      - ApiGatewayMethodPost
    Properties:
      RestApiId: !Ref ApiGatewayRestApi


  ProdStage:
    Type: AWS::ApiGateway::Stage
    DependsOn: ApiGatewayAccount
    Properties:
      StageName: prod
      RestApiId: !Ref ApiGatewayRestApi
      DeploymentId: !Ref ApiGatewayDeployment
      Description: "prod stage description"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
      AccessLogSetting:
        DestinationArn: !GetAtt MyLogGroup.Arn
        Format: "$context.extendedRequestId $context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] \"$context.httpMethod $context.resourcePath $context.protocol\" $context.status $context.responseLength $context.requestId"

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ProdStage
    Properties:
      Name: TestApiKey
      Description: CloudFormation API Key V1
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGatewayRestApi
          StageName: prod         


  LambdaGetInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GoLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/GET/dummy

  LambdaPostInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GoLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/POST/dummy

Outputs:
  ApiInvokeURL:
    Description: Invoke URL for the API
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/dummy"
  ApiKeyValue:
    Description: API Key value for testing
    Value: !Ref ApiKey  
